export const ComboBox = {
  name: "ComboBox1",
  type: "ComboBox",
  autoSize: false,
  autoTab: false,
  autoWordSelect: true,
  boundColumn: 1,
  columnCount: 1,
  columnHeads: false,
  columnWidths: "",
  controlSource: "",
  controlTipText: "",
  dragBehavior: "0 - fmDragBehaviotDisabled",
  dropButtonStyle: "1 - fmDropButtonStyleArrow ",
  enabled: true,
  enterFieldBehavior: "0 - fmEnterFiledBehaviorSelectAll",
  helpContextId: 0,
  hideSelection: true,
  imeMode: "0 - fmIMEModeNOControl",
  listRows: 8,
  listStyle: "0 - fmListStylePlain",
  listWidth: "0 pt",
  locked: false,
  isActive: false,
  matchEntry: "1 - fmMatchEntryComplete",
  matchRequired: false,
  maxLength: 0,
  mouseIcon: "(None)",
  rowSource: "",
  selectionMargin: true,
  showDropButtonWhen: "2 - fmShowDropButtonWhenAlways",
  tabIndex: 4,
  tabStop: true,
  tag: "",
  text: "",
  textColumn: -1,
  topIndex: -1,
  value: "",
  visible: true,
  left: "20px",
  top: "100px",
  width: "100px",
  height: "40px",
  zIndex: "1",
  backColor: "white",
  borderColor: "#eeeeee",
  border: "1px solid",
  borderStyle: "solid",
  font: "Arial, Helvetica, sans-serif",
  foreColor: "black",
  textAlign: "left",
  cursor: "default",
  specialEffect: "none",
  wordWrap: "break-word",
  overflow: "hidden",
  whiteSpace: "normal",
  backStyle:"1 - fmBackStyleOpaque",
  mousePointer:""
};
