export const CommandButton = {
  name: "CommandButton1",
  type: "CommandButton",
  accelerator: "",
  autoSize: false,
  caption: "CommandButton1",
  title: "",
  enabled: true,
  helpContextId: 0,
  mouseIcon: "(None)",
  picture: "(None)",
  picturePosition: "0 - fmPicturePositionLeftTop",
  tabIndex: 1,
  tabStop: false,
  tag: "",
  takeFocusOnClick: true,
  locked: false,
  visible: true,
  isActive: false,
  left: "20px",
  top: "100px",
  width: "100px",
  height: "40px",
  zIndex: "1",
  backColor: "white",
  borderColor: "#eeeeee",
  border: "1px solid",
  borderStyle: "solid",
  font: "Arial, Helvetica, sans-serif",
  foreColor: "black",
  textAlign: "left",
  cursor: "default",
  specialEffect: "none",
  wordWrap: "break-word",
  overflow: "hidden",
  whiteSpace: "normal",
  mousePointer:"",
  controlTipText:"",
  backStyle:""
};
