export const Image = {
  name: "Image1",
  type: "Image",
  controlTipText: "",
  enabled: true,
  mouseIcon: "(None)",
  picture: "(None)",
  pictureAlignment: "2 - fmPictureAlignmentCenter",
  pictureSizeMode: "0 - fmPictureSizeModeClip",
  pictureTiling: false,
  tag: "",
  visible: true,
  left: "20px",
  top: "100px",
  width: "100px",
  height: "40px",
  zIndex: "1",
  backColor: "white",
  borderColor: "#eeeeee",
  border: "1px solid",
  borderStyle: "solid",
  foreColor: "black",
  specialEffect: "none",
  position:"",
  mousePointer:"",
  autoSize:false,
  isActive: false,

};
