export const Label = {
  name: "Label1",
  type: "Label",
  accelerator: "",
  autoSize: false,
  caption: "Label1",
  title: "Label1",
  enabled: true,
  helpContextId: 0,
  mouseIcon: "(None)",
  picture: "(None)",
  picturePosition: "0 - fmPicturePositionLeftTop",
  tabIndex: 0,
  tabStop: false,
  tag: "",
  visible: true,
  isActive: false,
  left: "70px",
  top: "0px",
  width: "100px",
  height: "40px",
  zIndex: "1",
  border: "none",
  backColor: "white",
  borderColor: "ghostwhite",
  font: "Tahoma",
  foreColor: "black",
  textAlign: "left",
  specialEffect: "none",
  wordWrap: "break-word",
  overflow: "hidden",
  whiteSpace: "normal",
  mousePointer: "default",
  backStyle:""
};
