export const ListBox = {
  name: "ListBox1",
  type: "ListBox",
  boundColumn: 1,
  columnCount: 1,
  columnHeads: false,
  columnWidths: "",
  controlSource: "",
  controlTipText: "",
  enabled: true,
  helpContextId: 0,
  imeMode: "0 - fmIMEModeNOControl",
  integralHeight: true,
  listStyle: "0 - fmListStylePlain",
  locked: false,
  matchEntry: "0 - fmMatchEntryFirstLetter",
  mouseIcon: "(None)",
  multiSelect: "0 - fm-MousePointerDefault",
  rowSource: "",
  tabIndex: 6,
  tabStop: true,
  tag: "",
  text: "",
  textColumn: -1,
  topIndex: -1,
  value: "",
  isActive: false,
  visible: true,
  left: "20px",
  top: "100px",
  width: "100px",
  height: "40px",
  zIndex: "1",
  backColor: "white",
  borderColor: "#eeeeee",
  border: "1px solid",
  borderStyle: "solid",
  font: "Arial, Helvetica, sans-serif",
  foreColor: "black",
  textAlign: "left",
  cursor: "default",
  specialEffect: "none",
  wordWrap: "break-word",
  overflow: "hidden",
  whiteSpace: "normal",

};
