export const MultiPage = {
  name: "MultiPage1",
  type: "MultiPage",
  controlTipText: "",
  enabled: true,
  helpContextId: 0,
  multiRow: false,
  tabFixedHeight: 0,
  tabFixedWidth: 0,
  tabIndex: 13,
  tabOrientation: "0 - fmTabOrientationTop",
  tabStop: true,
  tag: "",
  value: "",
  visible: true,
  isActive: false,
  left: "20px",
  top: "100px",
  width: "100px",
  height: "40px",
  zIndex: "1",
  backColor: "white",
  font: "Arial, Helvetica, sans-serif",
  foreColor: "black",
  style:"",
  position:""
};
