export const OptionButton = {
  name: "OptionButton1",
  type: "OptionButton",
  caption: "OptionButton1",
  accelerator: "",
  alignment: "1 - fmAlignmentRight",
  autoSize: false,
  controlSource: "",
  controlTipText: "",
  enabled: true,
  groupName: "",
  helpContextId: 0,
  locked: false,
  mouseIcon: "(None)",
  picture: "(None)",
  picturePosition: "7 - fmPicturePositionAboveCenter",
  tabIndex: 10,
  tabStop: true,
  tripleState: false,
  isActive: false,
  tag: "",
  value: "",
  visible: true,
  left: "20px",
  top: "100px",
  width: "100px",
  height: "40px",
  zIndex: "1",
  backColor: "white",
  borderColor: "#eeeeee",
  border: "1px solid",
  backStyle: "solid",
  font: "Arial, Helvetica, sans-serif",
  foreColor: "black",
  textAlign: "left",
  mousePointer: "default",
  specialEffect: "none",
  wordWrap: "break-word",
  overflow: "hidden",
  whiteSpace: "normal",
  position: ""
 
};
