export const RefEdit = {
  name: "RefEdit1",
  type: "RefEdit",
  autoSize: false,
  autoTab: false,
  autoWordSelect: true,
  controlSource: "",
  controlTipText: "",
  dragBehavior: "0 - fmDragBehaviotDisabled",
  enabled: true,
  enterFieldBehavior: "0 - fmEnterFiledBehaviorSelectAll",
  enterKeyBehavior: false,
  helpContextId: 0,
  hideSelection: true,
  integralHeight: true,
  imeMode: "0 - fmIMEModeNoControl",
  locked: false,
  maxLength: 0,
  mouseIcon: "(None)",
  multiLine: false,
  passwordChar: "",
  scrollBars: "1 - fmScrollBarsNone",
  selectionMargin: true,
  tabIndex: 4,
  tabKeyBehavior: false,
  tabStop: false,
  tag: "",
  text: "",
  value: "",
  isActive: false,
  visible: true,
  left: "20px",
  top: "100px",
  width: "100px",
  height: "40px",
  zIndex: "1",
  backgroundColor: "white",
  borderColor: "#eeeeee",
  border: "1px solid",
  borderStyle: "solid",
  fontFamily: "Arial, Helvetica, sans-serif",
  forecolor: "black",
  textAlign: "left",
  mousePointer: "default",
  boxShadow: "none",
  wordWrap: "break-word",
  overflow: "hidden",
  whiteSpace: "normal",
  position:"",
  selLength:4,
  selStart:0,
    selText:"",
};
