export const SpinButton = {
  name: "SpinButton1",
  type: "SpinButton",
  controlSource: "",
  controlTipText: "",
  delay: 50,
  enabled: true,
  helpContextId: 0,
  max: 100,
  min: 0,
  mouseIcon: "(None)",
  orientation: "-1 - fmOrientationAuto",
  smallChange: 1,
  tabIndex: 13,
  tabStop: true,
  tag: "",
  value: "",
  visible: true,
  isActive: false,
  left: "20px",
  top: "100px",
  width: "100px",
  height: "40px",
  zIndex: "1",
  backColor: "white",
  font: "Arial, Helvetica, sans-serif",
  foreColor: "black",
  position: "",
  mousePointer: "",
  style: ""
};
