export const TabStrip = {
  name: "TabStrip1",
  type: "TabStrip",
  controlTipText: "",
  enabled: true,
  helpContextId: 0,
  mouseIcon: "(None)",
  multiRow: false,
  picture: "(None)",
  tabFixedHeight: 0,
  tabFixedWidth: 0,
  tabIndex: 13,
  tabOrientation: "0 - fmTabOrientationTop",
  tabStop: true,
  tag: "",
  value: "",
  visible: true,
  left: "20px",
  top: "100px",
  width: "100px",
  height: "40px",
  zIndex: "1",
  backColor: "white",
  font: "Arial, Helvetica, sans-serif",
  foreColor: "black",
  mousePointer: "default",
  position:"",
  style:"",
  isActive: false,
};
