export const ToggleButton = {
  name: "ToggleButton1",
  type: "ToggleButton",
  caption: "ToggleButton1",
  accelerator: "",
  autoSize: false,
  controlSource: "",
  controlTipText: "",
  enabled: true,
  helpContextId: 0,
  locked: false,
  mouseIcon: "(None)",
  picture: "(None)",
  picturePosition: "7 - fmPicturePositionAboveCenter",
  tabIndex: 11,
  tabStop: true,
  tripleState: false,
  tag: "",
  value: "",
  visible: true,
  isActive: false,
  left: "20px",
  top: "100px",
  width: "100px",
  height: "40px",
  zIndex: "1",
  backColor: "white",
  borderColor: "#eeeeee",
  border: "1px solid",
  borderStyle: "solid",
  font: "Arial, Helvetica, sans-serif",
  foreColor: "black",
  textAlign: "left",
  cursor: "default",
  specialEffect: "none",
  wordWrap: "break-word",
  overflow: "hidden",
  whiteSpace: "normal",
  groupName:"",
  backStyle:"",
  mousePointer:"",
  position:"",

};
